SeedV/SeedLang

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, csharp/src/SeedLang/Program.cs
- Fix test project path setting of dotnet test explorer
- Remove unused parameter args
- Re-format vscode json files (change indent to 2)
=> Fix test project path setting issue

.github/workflows/csharp.yml, .vscode/settings.json, csharp/src/SeedLang.X/SeedLang.X.csproj, grammars/SeedAst.asdl, grammars/SeedPython.g4, grammars/generate_parser.sh
- Fix license of SeedPython grammar file, the content of all the grammars will be refined in the future
- Change name of SeedAST.asdl
- Add Bash script to generate ANTLR4 parser
- Add step in Github csharp workflow to generate ANTLR4 parser
=> Generate ANTLR4 parser

.vscode/launch.json, csharp/src/SeedLang.Common/Language.cs, csharp/src/SeedLang.Common/ParseRule.cs, csharp/src/SeedLang.Common/ProgrammingLanguage.cs, csharp/src/SeedLang.Common/RunType.cs, csharp/src/SeedLang.Shell/Program.cs, csharp/src/SeedLang.Shell/SeedLang.Shell.csproj, csharp/src/SeedLang.X/PythonParser.cs, csharp/src/SeedLang.X/PythonVisitor.cs, csharp/src/SeedLang.X/SyntaxErrorListener.cs, csharp/src/SeedLang/Engine.cs, csharp/src/SeedLang/IEngine.cs, csharp/src/SeedLang/SeedLang.csproj, csharp/tests/SeedLang.X.Tests/PythonParserTests.cs, grammars/SeedPython.g4
Define the IEngine interface. Refine the SeedPython grammar file and the SeedPython parser to validate and parse a single expression and statement.
=> Define the IEngine interface

csharp/src/SeedLang.Block/BxfConstants.cs, csharp/src/SeedLang.Block/BxfObject.cs, csharp/src/SeedLang.Block/BxfReader.cs, csharp/src/SeedLang.Block/BxfWriter.cs, csharp/src/SeedLang.Block/SeedLang.Block.csproj, csharp/tests/SeedLang.Block.Tests/BxfTests.cs
More unit tests are also added.
=> Migrate from Newtonsoft.Json to System.Text.Json

csharp/src/SeedLang.Ast/AstStringBuilder.cs, csharp/src/SeedLang.Ast/AstWalker.cs, csharp/src/SeedLang.Ast/Executor.cs, csharp/src/SeedLang.Ast/Expressions.cs, csharp/src/SeedLang.Ast/NumberValue.cs, csharp/src/SeedLang.Ast/Statements.cs, csharp/src/SeedLang.Runtime/Events.cs, csharp/src/SeedLang.Runtime/VisualizerCenter.cs, csharp/src/SeedLang.Shell/Repl.cs, csharp/src/SeedLang.X/PythonVisitor.cs, csharp/src/SeedLang/Engine.cs, csharp/tests/SeedLang.Ast.Tests/AstNodesTests.cs, csharp/tests/SeedLang.Ast.Tests/ExecutorTests.cs, csharp/tests/SeedLang.X.Tests/PythonParserTests.cs, grammars/SeedPython.g4
=> Parse and execute the identifier expression and assignment statement

csharp/src/SeedLang/Block/BaseBlock.cs, csharp/src/SeedLang/Block/Converter.cs, csharp/src/SeedLang/Block/InlineTextParser.cs, csharp/src/SeedLang/Common/Message.cs, csharp/src/SeedLang/Common/TextRange.cs, csharp/src/SeedLang/X/CodeReferenceUtils.cs, csharp/src/SeedLang/X/SyntaxErrorStrategy.cs, csharp/tests/SeedLang.Tests/Block/ConverterTest.cs, csharp/tests/SeedLang.Tests/Block/InlineTextParserTests.cs
* Supports Validate and Parse separately
* Parses inline text strings with invalid tokens
* Reports error info via Diagnostic collection
* Remove unused code in unittests
=> Improve the Converter interface

csharp/benchmark/SeedLang.Benchmark/BinaryExpressionBenchmark.cs, csharp/src/SeedLang.Shell/Repl.cs, csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/AstWalker.cs, csharp/src/SeedLang/Ast/Executor.cs, csharp/src/SeedLang/Ast/Expressions.cs, csharp/src/SeedLang/Ast/Statements.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Runtime/Events.cs, csharp/src/SeedLang/Runtime/Operators.cs, csharp/src/SeedLang/Runtime/Values.cs, csharp/src/SeedLang/Runtime/VisualizerCenter.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/Ast/AstNodesTests.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorErrorTests.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorExpressionsTests.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorStatementsTests.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorTests.cs, csharp/tests/SeedLang.Tests/Ast/ExpressionsTests.cs, csharp/tests/SeedLang.Tests/Ast/MockupVisualizer.cs, csharp/tests/SeedLang.Tests/Ast/StatementsTest.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs, csharp/tests/SeedLang.Tests/Runtime/ValueTests.cs, grammars/SeedAst.asdl
- BooleanExpression
- BooleanConstantExpression
- NoneConstantExpression
- BlockStatement
- IfStatement
- WhileStatement
=> Add more AST nodes and implement execution of these nodes

csharp/src/SeedLang.Shell/Repl.cs, csharp/src/SeedLang/X/PythonVisitor.cs, csharp/tests/SeedLang.Tests/Runtime/ExecutorTests.cs, csharp/tests/SeedLang.Tests/X/PythonParserErrorTests.cs, csharp/tests/SeedLang.Tests/X/PythonParserTests.cs, grammars/SeedPython.g4
=> Add newline to separate simple statements

csharp/src/SeedLang.Shell/Repl.cs, csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/Executor.cs, csharp/src/SeedLang/Runtime/Operators.cs, csharp/src/SeedLang/Runtime/ValueHelper.cs, csharp/src/SeedLang/X/BlockInlineTextVisitor.cs, csharp/src/SeedLang/X/PythonVisitor.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorExpressionsTests.cs, csharp/tests/SeedLang.Tests/X/PythonParserTests.cs, grammars/Common.g4
=> Implement floor divide, power and modulo

csharp/src/SeedLang/X/SeedCalcVisitor.cs, csharp/tests/SeedLang.Tests/X/SeedCalcTests.cs
=> Fix expression statement visiting for SeedCalc

csharp/src/SeedLang.Shell/Repl.cs, csharp/src/SeedLang.Shell/SourceCode.cs, csharp/src/SeedLang.Shell/Theme.cs, csharp/tests/SeedLang.Tests/Runtime/ExecutorSeedCalcTests.cs
Fix #97 
I couldn't reproduce the first half part of this issue on the latest commit:
```
Input: 5+(
SeedCalc parsing result: 5, +, (, (
```
Added two test case for it.
The exception in SeedLang.Shell while running this code is fix in this PR.
=> Refactor source code input and output logic

csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/AstWalker.cs, csharp/src/SeedLang/Ast/Executor.cs, csharp/src/SeedLang/Ast/Expressions.cs, csharp/src/SeedLang/Ast/Statements.cs, csharp/src/SeedLang/Common/Message.cs, csharp/src/SeedLang/Common/SyntaxToken.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Runtime/HeapObject.cs, csharp/src/SeedLang/Runtime/Value.cs, csharp/src/SeedLang/Runtime/ValueHelper.cs, csharp/src/SeedLang/X/SeedPythonVisitor.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorErrorTests.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorStatementsTests.cs, csharp/tests/SeedLang.Tests/Ast/ExpressionsTests.cs, csharp/tests/SeedLang.Tests/Runtime/ExecutorTests.cs, csharp/tests/SeedLang.Tests/Runtime/ValueTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonErrorTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonListTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs, grammars/Common.g4, grammars/SeedPython.g4
Following bubble sort code can be run:
```python
array = [64, 34, 25, 12, 22, 11, 90]
n = 7
i = 0
while i < n:
j = 0
while j < n - i - 1:
if array[j] > array[j + 1]:
temp = array[j]
array[j] = array[j + 1]
array[j + 1] = temp
j = j + 1
i = i + 1
array
```
TODO: there might be some exceptions that are not handled.
=> Parse and execute list and subscript expressions

csharp/src/SeedLang.Shell/Program.cs, csharp/src/SeedLang.Shell/Repl.cs, csharp/src/SeedLang.Shell/SourceCode.cs, csharp/src/SeedLang.Shell/VisualizerManager.cs, grammars/SeedAst.asdl
Run SeedPython source file by following command:
```shell
dotnet run --project src/SeedLang.Shell -- -v All -f path_to_source_file
```
=> Run SeedPython file

csharp/src/SeedLang/Runtime/HeapObject.cs, csharp/src/SeedLang/Runtime/Value.cs, csharp/tests/SeedLang.Tests/Runtime/ValueTests.cs
=> Detect reference cycles in lists

csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/AstWalker.cs, csharp/src/SeedLang/Ast/Executor.cs, csharp/src/SeedLang/Ast/Expressions.cs, csharp/src/SeedLang/Ast/Statements.cs, csharp/src/SeedLang/Common/SyntaxToken.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/X/SeedPythonVisitor.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/Ast/ExpressionsTests.cs, csharp/tests/SeedLang.Tests/Ast/StatementsTest.cs, csharp/tests/SeedLang.Tests/X/SeedPythonDentLexerTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonErrorTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs, grammars/Common.g4, grammars/SeedAst.asdl, grammars/SeedPython.g4
Only parsing of function declaration, return statements and call expression nodes are implemented in this PR.
TODO in future PR:
- Add function type value object (include AST function object, native function object)
- Add environment frame chain to handle scoped variables (include local variables and function parameters)
- Execute function declaration, return statements and call expressions
=> Parse function declaration, return and call AST nodes

csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/AstWalker.cs, csharp/src/SeedLang/Ast/Environment.cs, csharp/src/SeedLang/Ast/Exceptions.cs, csharp/src/SeedLang/Ast/Executor.cs, csharp/src/SeedLang/Ast/Function.cs, csharp/src/SeedLang/Ast/Statements.cs, csharp/src/SeedLang/Common/Message.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Runtime/HeapObject.cs, csharp/src/SeedLang/Runtime/IFunction.cs, csharp/src/SeedLang/Runtime/NativeFunction.cs, csharp/src/SeedLang/Runtime/Value.cs, csharp/src/SeedLang/Runtime/ValueWrapper.cs, csharp/tests/SeedLang.Tests/Ast/EnvironmentTests.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorStatementsTests.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/Runtime/ExecutorTests.cs, csharp/tests/SeedLang.Tests/Runtime/ValueTests.cs, csharp/tests/SeedLang.Tests/Runtime/VisualizerCenterTests.cs
Following code is supported:
```python
def factorial(n):
if n == 1:
return 1
else:
return n * factorial(n - 1)
factorial(10)
```
=> Support function definition, call functions and return from functions

csharp/benchmark/SeedLang.Benchmark/FibBenchmark.cs, csharp/src/SeedLang/Interpreter/Chunk.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/Disassembler.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs, csharp/tests/SeedLang.Tests/Runtime/ExecutorBytecodeTests.cs
Following code can be executed by this PR:
```python
if a < b < c and e > f:
...
```
=> Compile boolean and comparison expressions

csharp/src/SeedLang/Common/Diagnostic.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
Fix #130 
Also removed some unnecessary test code.
=> Handle undefined variables in SeedVM

csharp/src/SeedLang/X/SeedPythonVisitor.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs
=> Fix empty return statement crash issue

csharp/src/SeedLang.Shell/Theme.cs, csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/AstWalker.cs, csharp/src/SeedLang/Ast/Executor.cs, csharp/src/SeedLang/Ast/Expressions.cs, csharp/src/SeedLang/Common/TokenInfo.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/ConstantCache.cs, csharp/src/SeedLang/Interpreter/Opcode.cs, csharp/src/SeedLang/Interpreter/VM.cs, csharp/src/SeedLang/Runtime/IValue.cs, csharp/src/SeedLang/Runtime/NativeFunctions.cs, csharp/src/SeedLang/Runtime/RunMode.cs, csharp/src/SeedLang/Runtime/Value.cs, csharp/src/SeedLang/Runtime/ValueWrapper.cs, csharp/src/SeedLang/X/SeedBlockInlineText.cs, csharp/src/SeedLang/X/SeedBlockInlineTextVisitor.cs, csharp/src/SeedLang/X/SeedPython.cs, csharp/src/SeedLang/X/SeedPythonVisitor.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorStatementsTests.cs, csharp/tests/SeedLang.Tests/Ast/ExpressionsTests.cs, csharp/tests/SeedLang.Tests/Helper/AstHelper.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/Runtime/ValueTests.cs, csharp/tests/SeedLang.Tests/Runtime/VisualizerCenterTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs, design/seed_vm.md, grammars/SeedAst.asdl
Reimplement this feature by adding a new `LOADNONE` opcode.
=> Add LOADNONE opcode to implement none constant expression

csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/Executor.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/Opcode.cs, csharp/src/SeedLang/Interpreter/VM.cs, csharp/src/SeedLang/Runtime/Operators.cs, csharp/src/SeedLang/Runtime/ValueHelper.cs, csharp/src/SeedLang/X/SeedBlockInlineTextVisitor.cs, csharp/src/SeedLang/X/SeedPythonVisitor.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/Ast/ExecutorExpressionsTests.cs, csharp/tests/SeedLang.Tests/Helper/MockupVisualizer.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs, csharp/tests/SeedLang.Tests/Runtime/NativeFunctionsTests.cs, csharp/tests/SeedLang.Tests/Runtime/ValueHelperTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs, design/seed_vm.md, examples/seedpython/scripts/dict.py, examples/seedpython/scripts/list.py, examples/seedpython/scripts/string.py, grammars/Common.g4
Support following code:
```python
print('python' in str)
print('super' in str)
print(8 in list)
print(None in list)
print('Age' in dict)
print('School' in dict)
```
=> Implement in keyword

csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/Notifications.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerNotificationTests.cs
The code of this PR is extracted from the previous abandoned PR #152. The reason of abandoning #152 is that we are going to re-design the  API of visualizer notifications. But some code for the `ForIn` loop variable assignment notification might be useful in the future.
=> Send assignment notifications for "ForIn" loop variables

.github/workflows/coverage.yml, README.md, csharp/tests/SeedLang.Tests/SeedLang.Tests.csproj
=> Measure code coverage of unit tests

csharp/src/SeedLang.Shell/VisualizerManager.cs, csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/Statements.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/Notifications.cs, csharp/src/SeedLang/Runtime/Events.cs, csharp/src/SeedLang/X/CodeReferenceUtils.cs, csharp/src/SeedLang/X/SeedPythonDentLexer.cs, csharp/src/SeedLang/X/SeedPythonVisitor.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/Ast/ExpressionsTests.cs, csharp/tests/SeedLang.Tests/Ast/StatementsTest.cs, csharp/tests/SeedLang.Tests/Helper/AstHelper.cs, csharp/tests/SeedLang.Tests/Helper/MockupVisualizer.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerNotificationTests.cs, csharp/tests/SeedLang.Tests/Runtime/NativeFunctionsTests.cs, csharp/tests/SeedLang.Tests/X/SeedBlockInlineTextTests.cs, csharp/tests/SeedLang.Tests/X/SeedCalcTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonDentLexerTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonDictTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonListTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonVTagTest.cs, examples/seedpython/scripts/bubble_sort.py, grammars/SeedPython.g4
Use following command to run bubble_sort.py to check the result of Tag statements
```shell
dotnet run --project csharp/src/SeedLang.Shell -- -v All -f examples/seedpython/scripts/bubble_sort.py
```
=> Implement multiple-line VTag statements and arguments

csharp/src/SeedLang.Shell/SourceCode.cs, csharp/src/SeedLang/X/SeedPythonDentLexer.cs, csharp/tests/SeedLang.Tests/Block/ModuleTests.cs, csharp/tests/SeedLang.Tests/ParseSyntaxErrorTokensTests.cs, csharp/tests/SeedLang.Tests/X/SeedBlockInlineTextTests.cs, csharp/tests/SeedLang.Tests/X/SeedCalcTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonDentLexerTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonDictTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonErrorTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonListTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs, grammars/SeedPython.g4
Fix #166 
Also fix a braces matching bug in SourceCode.cs in SeedLang.Shell.
=> Fix nested bracks parsing error

csharp/src/SeedLang.Shell/Executor.cs, csharp/src/SeedLang.Shell/Program.cs, csharp/src/SeedLang.Shell/VisualizerManager.cs, csharp/src/SeedLang/Interpreter/Chunk.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/Notifications.cs, csharp/src/SeedLang/Interpreter/VM.cs, csharp/src/SeedLang/Runtime/Events.cs, csharp/src/SeedLang/Runtime/NativeFunctions.cs, csharp/tests/SeedLang.Tests/Helper/MockupVisualizer.cs, csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/Interpreter/DisassemblerTest.cs
Also refactor VisualizerManager by reflection.
=> Implement FuncCalled and FuncReturned visualization events

csharp/src/SeedLang.Shell/Executor.cs, csharp/src/SeedLang/Ast/AstStringBuilder.cs, csharp/src/SeedLang/Ast/AstWalker.cs, csharp/src/SeedLang/Ast/Statements.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/NestedLoopStack.cs, csharp/src/SeedLang/Interpreter/VM.cs, csharp/src/SeedLang/X/SeedPythonVisitor.cs, csharp/src/SeedLang/X/VisitorHelper.cs, csharp/tests/SeedLang.Tests/EngineTest.cs, csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs, examples/seedpython/scripts/loop.py, examples/seedpython/scripts/while.py, grammars/SeedPython.g4
Support following code:
```python
for ch in "string":
if ch == "i":
break
print(ch)
```
Fix #155 
`continue` statement hasn't been fully implemented.
=> Implement break statements

csharp/src/SeedLang.Shell/VisualizerManager.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/CompilerHelper.cs, csharp/src/SeedLang/Interpreter/ExprCompiler.cs, csharp/src/SeedLang/Interpreter/Notifications.cs, csharp/src/SeedLang/Interpreter/VariableResolver.cs, csharp/src/SeedLang/Visualization/Events.cs, csharp/tests/SeedLang.Tests/CompilePythonTests.cs, csharp/tests/SeedLang.Tests/Helper/VisualizerHelper.cs, csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VariableResolverTests.cs, csharp/tests/SeedLang.Tests/SeedLang.Tests.csproj, examples/seedpython/scripts/dict.py
=> Implement subscript assignment notification

csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/CompilerHelper.cs, csharp/src/SeedLang/Interpreter/Notifications.cs, csharp/src/SeedLang/Visualization/Events.cs, csharp/tests/SeedLang.Tests/Helper/VisualizerHelper.cs, csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs
Fix #192 
The evaluation result will be `None` during VTagEntered notification, if any variable is not defined.
=> Try evaluating expressions for VTagEntered notifications

csharp/src/SeedLang.Shell/Executor.cs, csharp/src/SeedLang.Shell/VisualizerManager.cs, csharp/src/SeedLang/Common/Diagnostic.cs, csharp/src/SeedLang/Common/Message.cs, csharp/src/SeedLang/Engine.cs, csharp/src/SeedLang/Interpreter/Chunk.cs, csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/Disassembler.cs, csharp/src/SeedLang/Interpreter/Notifications.cs, csharp/src/SeedLang/Interpreter/Opcode.cs, csharp/src/SeedLang/Interpreter/VM.cs, csharp/src/SeedLang/Interpreter/VMProxy.cs, csharp/src/SeedLang/Runtime/VMState.cs, csharp/src/SeedLang/Visualization/IVM.cs, csharp/src/SeedLang/Visualization/VisualizerCenter.cs, csharp/tests/SeedLang.Tests/CompilePythonTests.cs, csharp/tests/SeedLang.Tests/Helper/VisualizerHelper.cs, csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs, csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMStateTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs, csharp/tests/SeedLang.Tests/PythonVisualizationTests.cs, csharp/tests/SeedLang.Tests/Visualization/VisualizerCenterTests.cs, design/seed_vm.md
=> Support Stop() from callback of notification events

.github/workflows/csharp.yml, csharp/src/SeedLang/SeedLang.csproj
* Upgrade ANTLR runtime version to 4.10.1
* Upgrade Antlr4BuildTasks to 10.4.0
* Setup correct java environment in Github VM to make Antlr4BuildTasks work
=> Upgrade ANTLR4 version to 4.10.1

csharp/src/SeedLang/Common/Message.cs, csharp/src/SeedLang/Runtime/HeapObject.cs, csharp/src/SeedLang/Runtime/VMValue.cs, csharp/tests/SeedLang.Tests/Runtime/VMValueTests.cs
=> Handle slice assign not iterable runtime error

csharp/src/SeedLang/X/SeedPythonDentLexer.cs, csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonDentLexerTests.cs
=> Fix extra tab in the last line parsing issue

csharp/src/SeedLang/Interpreter/Compiler.cs, csharp/src/SeedLang/Interpreter/CompilerHelper.cs, csharp/src/SeedLang/Interpreter/ExprCompiler.cs, csharp/src/SeedLang/Interpreter/Notifications.cs, csharp/src/SeedLang/Interpreter/Registers.cs, csharp/src/SeedLang/Interpreter/VM.cs, csharp/src/SeedLang/Interpreter/VariableResolver.cs, csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs, csharp/tests/SeedLang.Tests/Interpreter/NotificationsTests.cs, csharp/tests/SeedLang.Tests/Interpreter/VMNotificationTest.cs
There isn't new functions implemented in this PR.
- One critical bug fix for variable deleted notification logic.
- Replace temp register allocated notification with temp register freed notification to improve the performance.
=> Bug fix and performance optimization for variable tracking

.vscode/settings.json, csharp/src/SeedLang/Ast/Expressions.cs, design/seed_vm.md, grammars/SeedAst.asdl
=> Correct design and asdl documents

csharp/src/SeedLang.Shell/Program.cs, csharp/src/SeedLang/Common/LocalizedMessages.cs, csharp/tests/SeedLang.Tests/X/SeedCalcTests.cs, csharp/tests/SeedLang.Tests/X/SeedPythonErrorTests.cs
And, let SeedLang.Shell support a new option to set the locale of the SeedLang engine.
=> Localize SeedLang messages

csharp/src/SeedLang.Shell/SeedLang.Shell.csproj, csharp/src/SeedLang/SeedLang.csproj
Use a new version number to get ready for the next release of SeedLang.
=> Boost SeedLang version number to 0.3.0

csharp/src/SeedLang/Runtime/BuiltinsDefinition.cs, csharp/src/SeedLang/Runtime/HeapObject.cs, csharp/src/SeedLang/Runtime/HeapObjects.cs, csharp/src/SeedLang/Runtime/Module.cs, csharp/src/SeedLang/Runtime/RandomDefinition.cs, csharp/src/SeedLang/Runtime/ValueHelper.cs, csharp/tests/SeedLang.Tests/Runtime/HeapObjectTests.cs, csharp/tests/SeedLang.Tests/Runtime/RandomDefinitionTests.cs
Fix #238. Support following code:
```python
>>> import random
---------- Source ----------
1     import random
---------- Run ----------
>>> random.seed()
---------- Source ----------
1     random.seed()
---------- Run ----------
>>> random.random()
---------- Source ----------
1     random.random()
---------- Run ----------
0.7713335619893649
>>> random.randint(5, 10)
---------- Source ----------
1     random.randint(5, 10)
---------- Run ----------
10
>>> random.randrange(1, 10, 3)
---------- Source ----------
1     random.randrange(1, 10, 3)
---------- Run ----------
4
```
=> Implement the builtin random library
