SeedV/SeedLang

- utils/block_proto/app.js
- utils/block_proto/block_utils.js
- utils/block_proto/blocks.js
- utils/block_proto/test/block_utils_test.js
- utils/block_proto/test/blocks_test.js
Example commands:
1) Generate a simple string:
node . -b string -o out.svg -c 'Hello, World!'
2) Generate an expression that contains a number of number values, operators and variables:
node . -b expression -o out.svg -c '130,÷,num,-,(,factor,^,7e4,+,delta,),×,-3.1415926,>=,7,and,1,==,2'
> Support prototyping strings, variables, operators and expressions

- utils/block_proto/block_utils.js
- utils/block_proto/blocks.js
- utils/block_proto/test/block_utils_test.js
- utils/block_proto/test/blocks_test.js
Now the utility supports prototyping simple statements such as break, continue, return..., eval..., set...to.... E.g.,
node . -b set -o out.svg -c 'y|3.14,×,x
node . -b eval -o out.svg -c '(,x,+,y,),>=,z'
And, a manually stacked simple statements:
> Support prototyping simple statements 

- design/ast.md
- grammars/SeedAST.asdl
Suggest to use Zephyr Abstract Syntax Definition Language as the specification of SeedAST. The final C# code of SeedAST can be written by hand or generated from ASDL file by a tool.
> Add ast design and asdl file for SeedAST

- .editorconfig
See https://google.github.io/styleguide/csharp-style.html
- Names of classes, methods, enumerations, public fields, public properties, namespaces: PascalCase.
- Names of local variables, parameters: camelCase.
- Names of private, protected, internal and protected internal fields and properties: _camelCase.
- Naming convention is unaffected by modifiers such as const, static, readonly, etc.
> Update .editorconfig based on Google C# style

- csharp/src/SeedLang.Ast/Expressions.cs
- csharp/src/SeedLang.Block/Parser.cs
- csharp/src/SeedLang.Block/SeedLang.Block.csproj
- csharp/src/SeedLang.X/BaseParser.cs
- csharp/src/SeedLang.X/BlockParser.cs
- csharp/src/SeedLang.X/BlockVisitor.cs
- csharp/src/SeedLang.X/PythonParser.cs
- csharp/src/SeedLang/Engine.cs
- csharp/tests/SeedLang.Block.Tests/ParserTest.cs
- csharp/tests/SeedLang.X.Tests/BlockParserTests.cs
- csharp/tests/SeedLang.X.Tests/PythonParserTests.cs
- grammars/Common.g4
- grammars/SeedBlock.g4
- grammars/SeedPython.g4
- grammars/generate_parser.bat
- grammars/generate_parser.sh
The block parser can parse text source code of block programs and convert text expression source code to a list of BaseBlock.
> Implement block parser

- csharp/src/SeedLang.Shell/SeedLang.Shell.csproj
- csharp/src/SeedLang/SeedLang.csproj
Add metadata so that SeedLang can be published to NuGet manually. Will add a versioning and publishing script to aotumate the process.
See the published versions at https://www.nuget.org/packages/SeedLang/
It sounds like a promising way to publish SeedLang to NuGet first then import the package to Unity (via a third-party extension, https://github.com/GlitchEnzo/NuGetForUnity). Although, there is still an unsolved dependency - System.Text.Json is failed to run in Unity - I will do more tests and try to fix it (e.g. by reverting back to Newtonsoft.Json) shortly.
> Add NuGet package metadata

- csharp/src/SeedLang/Block/BxfConstants.cs
- csharp/src/SeedLang/Block/BxfObject.cs
- csharp/src/SeedLang/Block/BxfReader.cs
- csharp/src/SeedLang/Block/BxfWriter.cs
- csharp/src/SeedLang/SeedLang.csproj
- csharp/tests/SeedLang.Tests/Block/BxfTests.cs
Unity has no official support of .Net 5.0 for now. Although it's possible to import NuGet package System.Text.Json for netstandard 2.0, the dependencies are very complex and hard to maintain. We have to manually choose and import 7 DLLs and disable "Validate References" for them in Unity.
With the solution to depend on Newtonsoft.Json, it's easy to import SeedLang.dll to Unity project without importing Newtonsoft.Json since Unity already provides one by default.
Please take a look at the experimental branch https://github.com/aha-001/SeedCalc/tree/wip_wixette_integration to see how to import SeedLang.dll into a Unity project and run a SeedLang executor in Unity scripts.
There are behavior differences between System.Text.Json and Newtonsoft.Json, especially in the strict deserialization …
> Revert back from System.Text.Json to Newtonsoft.Json

- csharp/src/SeedLang/Block/BxfReader.cs
- csharp/src/SeedLang/Block/Converter.cs
- csharp/src/SeedLang/Block/IEditable.cs
- csharp/src/SeedLang/Block/Module.cs
- csharp/src/SeedLang/Block/OperatorBlock.cs
- csharp/src/SeedLang/Block/PrimitiveValueBlock.cs
- csharp/src/SeedLang/Common/Diagnostic.cs
- csharp/src/SeedLang/Common/DiagnosticCollection.cs
- csharp/src/SeedLang/Common/DiagnosticException.cs
- csharp/src/SeedLang/X/SyntaxErrorStrategy.cs
- csharp/tests/SeedLang.Tests/Common/DiagnosticCollectionTests.cs
- csharp/tests/SeedLang.Tests/Common/DiagnosticExceptionTests.cs
- csharp/tests/SeedLang.Tests/Common/DiagnosticTests.cs
* Add MessageId to Diagnostic
* Refactor DiagnosticCollection to make reporting easier
* Add DiagnosticException for internal components to throw diagnostics
* Make Diagnostic mutable so that outside logic can refill info in
after catching a diagnostic via an exception (a temp solution)
> Include MessageId in Diagnostic. Closes #62

- csharp/src/SeedLang.Shell/Repl.cs
- csharp/src/SeedLang/Ast/AstNode.cs
- csharp/src/SeedLang/Ast/AstStringBuilder.cs
- csharp/src/SeedLang/Ast/Executor.cs
- csharp/src/SeedLang/Ast/Expressions.cs
- csharp/src/SeedLang/Ast/Statements.cs
- csharp/src/SeedLang/Block/InlineTextVisitor.cs
- csharp/src/SeedLang/Runtime/Events.cs
- csharp/src/SeedLang/X/BaseParser.cs
- csharp/src/SeedLang/X/PythonVisitor.cs
- csharp/src/SeedLang/X/VisitorHelper.cs
- csharp/tests/SeedLang.Tests/Ast/AstNodesTests.cs
- csharp/tests/SeedLang.Tests/Ast/ExecutorTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
- csharp/tests/SeedLang.Tests/Runtime/VisualizerCenterTests.cs
- csharp/tests/SeedLang.Tests/X/PythonParserTests.cs
- grammars/Common.g4
- grammars/SeedPython.g4
- The source code range could be BlockRange or TextRange.
- The range information is embedded in the AST node structure now.
- The range information is notified along with visualization events.
- SeedLang shell can highlight current visualized expression pf SeedPython.
Known issue: left and right parenthesis are not counted in the range corrected, because parenthesis information is removed from AST nodes. Need another way to handle it.
> Add source code range information in all AST nodes

- .github/workflows/csharp.yml
- .vscode/launch.json
- csharp/benchmark/SeedLang.Benchmark/SeedLang.Benchmark.csproj
- csharp/src/SeedLang.Shell/SeedLang.Shell.csproj
- csharp/src/SeedLang/SeedLang.csproj
- csharp/tests/SeedLang.Tests/SeedLang.Tests.csproj
Upgrade dotnet framework from 5.0 to 6.0 for shell, unit test and benchmark projects, because arm64 Mac osx is support in dotnet v6. There is significant performance increment in this version for development on Apple M1 laptop.
> Upgrade to dotnet 6.0

- csharp/src/SeedLang.Shell/Program.cs
- csharp/src/SeedLang.Shell/Repl.cs
- csharp/src/SeedLang/Ast/AstStringBuilder.cs
- csharp/src/SeedLang/Ast/AstWalker.cs
- csharp/src/SeedLang/Ast/Executor.cs
- csharp/src/SeedLang/Ast/Expressions.cs
- csharp/src/SeedLang/Interpreter/Compiler.cs
- csharp/src/SeedLang/Interpreter/VMValue.cs
- csharp/src/SeedLang/Runtime/Events.cs
- csharp/src/SeedLang/Runtime/Executor.cs
- csharp/src/SeedLang/Runtime/Operators.cs
- csharp/src/SeedLang/Runtime/SeedXLanguage.cs
- csharp/src/SeedLang/Runtime/ValueHelper.cs
- csharp/src/SeedLang/Runtime/Values.cs
- csharp/src/SeedLang/Runtime/VisualizerCenter.cs
- csharp/src/SeedLang/X/BaseParser.cs
- csharp/src/SeedLang/X/BlockInlineTextParser.cs
- csharp/src/SeedLang/X/BlockInlineTextVisitor.cs
- csharp/src/SeedLang/X/PythonParser.cs
- csharp/src/SeedLang/X/PythonVisitor.cs
- csharp/src/SeedLang/X/VisitorHelper.cs
- csharp/tests/SeedLang.Tests/Ast/AstNodesTests.cs
- csharp/tests/SeedLang.Tests/Ast/ExecutorTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/VMValueTests.cs
- csharp/tests/SeedLang.Tests/Runtime/ExecutorTests.cs
- csharp/tests/SeedLang.Tests/Runtime/ValueTests.cs
- csharp/tests/SeedLang.Tests/X/PythonParserTests.cs
- grammars/Common.g4
- grammars/SeedBlockInlineText.g4
- grammars/SeedPython.g4
Compare expressions with AST execution is implemented, like:
`1 < 2 < 3 == 3`
Bytecode execution hasn't implemented.
> Add compare expressions and implement AST execution

- csharp/src/SeedLang.Shell/Repl.cs
- csharp/src/SeedLang/Block/Converter.cs
- csharp/src/SeedLang/Common/Message.cs
- csharp/src/SeedLang/Runtime/Executor.cs
- csharp/src/SeedLang/Runtime/SeedXLanguage.cs
- csharp/src/SeedLang/SeedLang.csproj
- csharp/src/SeedLang/X/BaseParser.cs
- csharp/src/SeedLang/X/SeedBlockInlineText.cs
- csharp/src/SeedLang/X/SeedBlockInlineTextVisitor.cs
- csharp/src/SeedLang/X/SeedCalc.cs
- csharp/src/SeedLang/X/SeedCalcVisitor.cs
- csharp/src/SeedLang/X/SeedPython.cs
- csharp/src/SeedLang/X/SeedPythonVisitor.cs
- csharp/tests/SeedLang.Tests/X/SeedBlockInlineTextTests.cs
- csharp/tests/SeedLang.Tests/X/SeedCalcTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonErrorTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonTests.cs
- grammars/Common.g4
- grammars/SeedCalc.g4
Fix #93
- Support `+`, `-`, `*`, `/`, `(`, `)` in SeedCalc
- Support unary expressions like `1 + +2`, `1 + -2`
- Report syntax errors for unary expressions like `1+ + -2`
- Support unary expressions like `1 + +(-(+2))`
One point need be considered later:
Our original idea is all the SeedX languages can be converted to other languages through AST, because they all support same syntax units. But SeedCalc only support very simple expressions. It cannot be converted from or to other languages.
> Implement SeedCalc language

- csharp/src/SeedLang.Shell/Program.cs
- csharp/src/SeedLang.Shell/Repl.cs
- csharp/src/SeedLang.Shell/SourceCode.cs
- csharp/src/SeedLang.Shell/VisualizerManager.cs
- csharp/src/SeedLang/X/SeedPythonDentLexer.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonDentLexerTests.cs
- Visualizers can be enabled separately, only `Eval` visualizer is enabled by default.
```shell
dotnet run --project src/SeedLang.Shell -- -v All     # enable all visualizers, include Assignment, Binary, Comparison, Eval
dotnet run --project src/SeedLang.Shell -- -v Binary Eval    # enable Binary and Eval visualizers
```
- Input multi-line source code. Please run following code for testing:
```shell
>>> i = 1
>>> sum = 0
>>> while i < 10:
...   sum = sum + i
...   i = i + 1
...
>>> sum
```
> Refactor SeedLang Shell

- csharp/src/SeedLang/Ast/Expressions.cs
- csharp/src/SeedLang/Runtime/ValueHelper.cs
- csharp/src/SeedLang/X/BaseParser.cs
- csharp/src/SeedLang/X/VisitorHelper.cs
- csharp/tests/SeedLang.Tests/X/SeedCalcTests.cs
- grammars/SeedCalc.g4
- Fix #112: Handles SeedCalc expressions with newlines.
- Fix #113: Checks overflow runtime errors for number constant expressions.
> Fix issue #112, #113

- README.nuget.md
- RELEASING.md
- csharp/src/SeedLang.Shell/SeedLang.Shell.csproj
- csharp/src/SeedLang/SeedLang.csproj
* Update version number to 0.2.0
* Add a short README for NuGet release
* Update the process described in RELEASING.md
See https://www.nuget.org/packages/SeedLang for the preview release based on this PR.
I think SeedLang is ready for a formal "minor" release - since the SeedCalc language is almost 100% ready and will be formally used by the first release of SeedCalc. We will create a formal release entry both on GitHub and on NuGet.
We can add a very short intro in GitHub's release notes to clarify that only SeedCalc is ready while other languages like SeedPython are still in progress.
> Update version number for a formal NuGet release

- .github/workflows/benchmark.yml
- csharp/benchmark/SeedLang.Benchmark/update_wiki.sh
Fix #79 
Only do benchmarks and upload the results to wiki when a PR is merge and push to the main branch, because the benchmark process is very slow.
> Add a GitHub CI action to upload benchmark results to wiki

- csharp/src/SeedLang/Ast/Expressions.cs
- csharp/src/SeedLang/Interpreter/Compiler.cs
- csharp/src/SeedLang/Runtime/NativeFunctions.cs
- csharp/src/SeedLang/X/SeedBlockInlineText.cs
- csharp/src/SeedLang/X/SeedPythonVisitor.cs
- csharp/src/SeedLang/X/VisitorHelper.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
- csharp/tests/SeedLang.Tests/Runtime/ExecutorPythonTests.cs
- csharp/tests/SeedLang.Tests/X/SeedBlockInlineTextTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs
- grammars/Common.g4
Following code can be run by SeedVM:
```python
array = []
for i in range(5):
array.append(i)
array
```
> Implement attribute statements for build-in value types

- .github/workflows/benchmark.yml
- csharp/benchmark/SeedLang.Benchmark/ParserBenchmark.cs
- csharp/benchmark/SeedLang.Benchmark/Program.cs
- csharp/benchmark/SeedLang.Benchmark/SeedLang.Benchmark.csproj
- csharp/benchmark/SeedLang.Benchmark/update_wiki.sh
* Add a separate benchmark for the syntax token parser.
* Add commandline options to SeedLang.Benchmark to choose benchmark to run.
> Add parser benchmark

- csharp/src/SeedLang/Ast/Expressions.cs
- csharp/src/SeedLang/Runtime/HeapObject.cs
- csharp/src/SeedLang/X/SeedPythonDentLexer.cs
- csharp/src/SeedLang/X/SeedPythonVisitor.cs
- csharp/src/SeedLang/X/VisitorHelper.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonDentLexerTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs
- examples/seedpython/scripts/string.py
- Fix first line comment parsing issue
- Move `Unescape` operation from `HeapObject` to `StringContent` factory method, because we should only do unescape for constant strings read from source code.
- Refactoring some unit test cases for easy debugging.
> Fix first line comment parsing issue

- csharp/src/SeedLang/Ast/Executor.cs
- csharp/src/SeedLang/Interpreter/Compiler.cs
- csharp/src/SeedLang/Interpreter/NestedJumpStack.cs
- csharp/src/SeedLang/Interpreter/VM.cs
- csharp/src/SeedLang/Runtime/ValueHelper.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
- csharp/tests/SeedLang.Tests/Runtime/ExecutorPythonTests.cs
Fix #134 
Supports following code:
```python
1 < 2 < 3
1 < 2 == 3
1 < 2 < 3 and 1 < 2 == 3
1 < 2 < 3 or 1 < 2 == 3
None == None
None != None
```
> Implement boolean and comparison expressions

- csharp/src/SeedLang/Ast/AstStringBuilder.cs
- csharp/src/SeedLang/Ast/AstWalker.cs
- csharp/src/SeedLang/Ast/Executor.cs
- csharp/src/SeedLang/Ast/Expressions.cs
- csharp/src/SeedLang/Common/Message.cs
- csharp/src/SeedLang/Interpreter/Compiler.cs
- csharp/src/SeedLang/Interpreter/Opcode.cs
- csharp/src/SeedLang/Interpreter/VM.cs
- csharp/src/SeedLang/Runtime/HeapObject.cs
- csharp/src/SeedLang/Runtime/IValue.cs
- csharp/src/SeedLang/Runtime/NativeFunctions.cs
- csharp/src/SeedLang/Runtime/Value.cs
- csharp/src/SeedLang/Runtime/ValueHelper.cs
- csharp/src/SeedLang/Runtime/ValueWrapper.cs
- csharp/src/SeedLang/X/SeedPythonVisitor.cs
- csharp/src/SeedLang/X/VisitorHelper.cs
- csharp/tests/SeedLang.Tests/Ast/ExecutorStatementsTests.cs
- csharp/tests/SeedLang.Tests/Helper/AstHelper.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/DisassemblerTest.cs
- csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs
- csharp/tests/SeedLang.Tests/Runtime/HeapObjectTests.cs
- csharp/tests/SeedLang.Tests/Runtime/NativeFunctionsTests.cs
- csharp/tests/SeedLang.Tests/Runtime/ValueTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonDictTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonErrorTests.cs
- design/seed_vm.md
- examples/seedpython/scripts/dict.py
- grammars/Common.g4
- grammars/SeedPython.g4
- Implement Dict for SeedPython, support following code now
```python
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
print("dict['Name']:", dict['Name'])  # dict['Name']: Zara
print("dict['Age']:", dict['Age'])  # "dict['Age']: 7
dict['Age'] = 8
dict['School'] = "DPS School"
print("dict['Age']:", dict['Age'])  # dict['Age']: 8
print("dict['School']:", dict['School'])  # dict['School']: DPS School
```
- Change the underlying data structure of Tuple to support hash code calculation for Dict.
> Implement Dict

- .github/workflows/coverage.yml
- README.md
Change to Codecov, because it has more features than coveralls.io. And also add a badge for Github build pass.
When comparing Coveralls vs Codecov, the Slant community recommends Codecov for most people. In the question“What are the best code coverage services?” Codecov is ranked 1st while Coveralls is ranked 3rd. The most important reason people chose Codecov is:
Codecov is free for up to 5 users and open source repositories on Github, Bitbucket, and Gitlab.
> Change coverage service from coveralls.io to Codecov

- csharp/src/SeedLang.Shell/SeedLang.Shell.csproj
- csharp/src/SeedLang/SeedLang.csproj
This new version number is used for releasing onto NuGet and being used by SeedLangExamples.
> Increase patch number of versions

- csharp/src/SeedLang/Ast/AstDumper.cs
- csharp/src/SeedLang/Ast/Statements.cs
- csharp/src/SeedLang/Interpreter/Compiler.cs
- csharp/src/SeedLang/SeedLang.csproj
- csharp/src/SeedLang/X/SeedPythonVisitor.cs
- csharp/src/SeedLang/X/VisitorHelper.cs
- csharp/tests/SeedLang.Tests/Ast/StatementsTest.cs
- csharp/tests/SeedLang.Tests/Helper/AstHelper.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonContainerTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonExpressionTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonStatementTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonVTagTest.cs
- examples/seedpython/scripts/sorting/merge_sort.py
- grammars/SeedPython.g4
Fix #198 
Following code is supported:
```python
a = b = 0
a = a[1] = [1, 2, 3]
```
> Implement chained assignment statement

- csharp/benchmark/SeedLang.Benchmark/FibBenchmark.cs
- csharp/benchmark/SeedLang.Benchmark/SumBenchmark.cs
- csharp/src/SeedLang.Shell/VisualizerManager.cs
- csharp/src/SeedLang/Interpreter/Compiler.cs
- csharp/src/SeedLang/Interpreter/CompilerHelper.cs
- csharp/src/SeedLang/Interpreter/ExprCompiler.cs
- csharp/src/SeedLang/Interpreter/Notifications.cs
- csharp/src/SeedLang/Interpreter/Registers.cs
- csharp/src/SeedLang/Interpreter/VM.cs
- csharp/src/SeedLang/Interpreter/VariableResolver.cs
- csharp/src/SeedLang/Visualization/EventData.cs
- csharp/src/SeedLang/Visualization/Events.cs
- csharp/src/SeedLang/Visualization/VisualizerCenter.cs
- csharp/tests/SeedLang.Tests/Helper/VisualizerHelper.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompileNotificationTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/NotificationsTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/VMNotificationTest.cs
- csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs
- csharp/tests/SeedLang.Tests/Visualization/VisualizerCenterTests.cs
- examples/seedpython/scripts/sorting/bubble_sort.py
- examples/seedpython/scripts/sorting/bubble_sort_2.py
- examples/seedpython/scripts/sorting/insertion_sort.py
- Change `Binary` and `Comparison` events to include variable information.
- Remove `SubscriptAssignment` events, and combine it into `Assignment` events.
- Remove `Boolean` and `Unary` events. It seems that these events are not useful now.
After this change, the `Compare VTag` is not needed any more. Please run following command to see the notification of `Assignment`, `Binary` and `Comparison`.
```shell
dotnet run --project csharp/src/SeedLang.Shell -- -v "*" -f examples/seedpython/scripts/sorting/bubble_sort.py
```
> Include variable information into assignment, binary and comparison notification events

- csharp/src/SeedLang/Interpreter/Compiler.cs
- csharp/src/SeedLang/Interpreter/ExprCompiler.cs
- csharp/tests/SeedLang.Tests/Interpreter/CompilerTests.cs
- csharp/tests/SeedLang.Tests/Interpreter/VMTests.cs
Fix #159 
Support following code now:
```python
def is_even(n):
return n % 2 == 0
for n in range(10):
if n < 5 and is_even(n):
print(n)
```
> Compile non-comparison and non-boolean expressions in the boolean expressions

- csharp/src/SeedLang.Shell/VisualizerManager.cs
- csharp/src/SeedLang/Visualization/Events.cs
Fix #217 
The client could access the value of assignment events by:
```csharp
double number = assignment.RValue.Value.AsNumber();
```
> Change field name from Value to RValue for assignment events

- csharp/src/SeedLang.Shell/Executor.cs
- csharp/src/SeedLang.Shell/Program.cs
- csharp/src/SeedLang.Shell/VisualizerManager.cs
- example_scripts/seedpython/hanoi.py
Add indention to SeedLang.Shell for the FuncCalled and FuncReturend visualizers, so that the function call stack in the runtime can be displayed clearly.
For example, use SeedLang.Shell to show the call stack of the Tower of Hanoi algorithm:
```shell
dotnet run --project src/SeedLang.Shell -- -f ../example_scripts/seedpython/hanoi.py -v "Func*"
SeedLang.Shell 0.2.1-preview20220728155708
Copyright 2021-2022 The SeedV Lab.
Enabled Visualizers: FuncCalled, FuncReturned
---------- Source ----------
1     def move(n, source, target, auxiliary):
2         if n <= 0:
3             return
4         move(n - 1, source, auxiliary, target)
5         print('Tower ' + source + ' -> Tower ' + target)
6         move(n-1, auxiliary, target, source)
7     
8     
9     num = 3
10    move(num, 'A', 'B', …
```
> Support indention for the Func* visualizers

- csharp/src/SeedLang/Common/LocalizedMessages.cs
- csharp/src/SeedLang/Common/Message.cs
- csharp/tests/SeedLang.Tests/Common/MessageTests.cs
- csharp/tests/SeedLang.Tests/X/SeedPythonErrorTests.cs
With this PR, SeedLang.Shell outputs error messages in the following way (only SyntaxErrorMissingToken2 is localized in this PR):
```
>>> def a()
---------- Source ----------
1     def a()
---------- Compile Error ----------
1     def a()
: 20220809205400297 Fatal (SeedLang.X) <> [Ln 1, Col 7 - Ln 1, Col 7] 29: Missing token. Found token: '\n'. Expected token: ':'
: 20220809205400299 Fatal (SeedLang.X) <> [Ln 2, Col 0 - Ln 2, Col -1] 28: SyntaxErrorInputMismatch '<EOF>' INDENT
```
After setting the current locale in SeedLang.Shell with
```
CultureInfo.CurrentCulture = new CultureInfo("zh-CN");
```
SeedLang.Shell outputs Chinese info like below:
```
>>> def a()
---------- Source ----------
1     def a()
---------- Compile Error ----------
1     def a()
: 20220809210408162 Fatal …
```
> Support localized messages

- docs/_config.yml
- docs/getting_started.md
- docs/index.md
Relative links to *.md are broken on the GitHub pages site https://seedv.github.io/SeedLang/ (those links worked on local server instead)
I tried to fix broken links with the following changes:
1. Add `baseurl: "/SeedLang"` to the jekyall config file.
2. Prepend `{{ site.baseurl }}` to each relative *.md link.
A local test proves the change works for relative links. But I am not quite sure this will work well on GitHub pages - depending on the push result after this PR is merged.
> Fix broken relative links
